### PR TITLE
Added more jobs in jobs.json

### PR DESCRIPTION
**Pull request by Anupam1603**
Contains some new job roles , most of them are not known to everyone . I hope it helps .

### CODE REVIEW

**Comment by GeekGuy-29** [comment]
Thanks @Anupam1603 for your precious contribution,
Really means a lot!
Happy Hacktoberfest!
<3

**Comment by Anupam1603** [comment]
Hey @GeekGuy-29  I had contributed 2 PR in your repository and both of them are showing as excluded  by the hacktober fest team . Can you explain the reason ?
Screenshot (214)

**Comment by GeekGuy-29** [comment]
@Anupam1603 I too don't know why.. I asked about it in the server, they said this won't happen
But idk,
But don't you bother there are thousands of repository to contribute, you should check those as well 
Don't loose hope buddy
At this point I can't do anything as well
If this situation prevails, I'll private this repo and won't waste someone else's time

**Comment by Anupam1603** [comment]
Hey can  i try to do another pr? 
or you have archived the repo?

**Comment by GeekGuy-29** [comment]
@Anupam1603 I haven't archived the repo, I have just removed the repo from being included in Hacktoberfest that's it
At the end of the day, this project will be open for contribution and, every PR will be considered!

**Comment by Anupam1603** [comment]
That's means any pr in it will not be considered for hacktober?

**Pull request merged**
