### PR TITLE
Added New Jobs

### PR DESCRIPTION
**Pull request by AK-codingmaniac**
Issue #3  :-
I have added some new jobs which I thought should be there in the repo
Please see to it and if it is not correct,then ping me otherwise merge it as soon as possible for HacktoberFest 2022

### CODE REVIEW

**Comment by GeekGuy-29** [comment]
Hey @AK-codingmaniac there are some conflicts in the file, please do resolve them
Sorry for the trouble <3

**Comment by AK-codingmaniac** [comment]
I can't see any conflicts in the file

**Comment by GeekGuy-29** [comment]
Screenshot 2022-10-08 at 12 23 15 AM

Have a look

**Comment by AK-codingmaniac** [comment]
Ok i will work on it

**Pull request closed without merging**
