### PR TITLE
Rendering links and added tabular formatting to fields, Added Emoji file to script

### PR DESCRIPTION
**Pull request by A-Spiral-Forge**
@GeekGuy-29 Please review this. 
Issue reference: #8 

image
image
image

### CODE REVIEW

**Comment by GeekGuy-29** [comment]
That's excellent @A-Spiral-Forge you're a genie!!
Thank you so much man!!

**Comment by A-Spiral-Forge** [comment]
@GeekGuy-29 No problem bro. We will make it together❤

**Comment by GeekGuy-29** [comment]
@A-Spiral-Forge I wanted to ask one thing, UI/UX for the website is being built so, once hard coded in HTML, can you in-lay the functionalities ??
As in, if you see the conversation in #7 you'll get to see I've sent in a design and in that there are buttons so, can you patch the script of each JSON files with the buttons?

**Comment by A-Spiral-Forge** [comment]
@GeekGuy-29 It's not a big deal. We are dynamically rendering the data so just changing the tag in JS file can change the formatting. We can do this once the design is completely ready for data rendering.

**Comment by GeekGuy-29** [comment]
Cool @A-Spiral-Forge 
I'll ping you as soon as I have something for you
Until then take care and Happy Hacktoberfest <3

**Comment by A-Spiral-Forge** [comment]
@GeekGuy-29 Sure. Happy Hacktoberfest <3

**Pull request merged**
