### PR TITLE
Update about Backend Developer

### PR DESCRIPTION
**Pull request by impetus007**

### CODE REVIEW

**Comment by Guptaanvi** [comment]
I wanna assist this work

**Comment by GeekGuy-29** [comment]
@Guptaanvi You can contribute as much as you want, I just want you to work in the updated scripts 
Thank you !!
💖

**Comment by impetus007** [comment]
Sure

**Comment by GeekGuy-29** [comment]
Alright @Guptaanvi see there's a pattern of the code
Just follow the pattern and I guess if you'll read the code, you'll totally understand what it says 
Lemme know if you're unable to understand what I've said
💖

**Pull request closed without merging**
